feature/dependabot
mecha-ci/hyperbuild pull request #12
Opened 2023-04-02 17:09 UTC by dirk39

2023-04-02 19:55 UTC, ludusrusso approved these changes
LGTM

2023-04-03 09:41 UTC, omissis requested changes

2023-04-03 09:41 UTC, omissis commented on .github/dependabot.yaml
> +    open-pull-requests-limit: 1
missing nl at eof

2023-04-03 09:41 UTC, omissis commented on docs/arch/0007-dependency-alert-tool.md
> +# 4. Dependency alert tool
```suggestion
# 7. Dependency alert tool
```

2023-04-03 10:05 UTC, omissis requested changes

2023-04-03 10:05 UTC, omissis commented on docs/arch/0007-dependency-alert-tool.md
> +# 7. Dependency alert tool
```suggestion
# 6. Dependency alert tool
```

2023-04-03 10:05 UTC, omissis commented on docs/arch/0007-dependency-alert-tool.md
I just noticed there's no ADR 6 :D

2023-04-03 10:16 UTC, dirk39 commented on docs/arch/0007-dependency-alert-tool.md
I thought that the #13 comes with a new ADR 😓 Let me update

2023-04-03 17:02 UTC, omissis approved these changes

2023-04-03 17:02 UTC, merged